/***********************************************************************
  TopicMap : Web application for visualizing a news map generated by TopicMaps
  Authors: Sumin Hong (hsue0606@gmail.com), U Kang (ukang@snu.ac.kr)
  Data Mining Lab., Seoul National University

-------------------------------------------------------------------------
File: user.js
 - a Database Schema for participant information in user study.

Version: 1.0
***********************************************************************/

var mongoose = require('mongoose');

var userSchema = new mongoose.Schema({
  userid: String,           // the user id of participant
  topic: String,            // the topic given to the participant
  nowflag: Number,          // the participant's status value
  conflag: [Number],        // A value indicating whether each map has a connection point
  dataset: [String],        // the two maps generated by TopicMap and ToT
  bestMap: String,          // A value that stores which of the two maps is good
  eachMap: {                // A value that stores the result of answering the four questions for each map.
    dataset1 : [String],
    dataset2 : [String]
  }
});

module.exports = mongoose.model("user",userSchema);
